### ISSUE TITLE
Closing a single connection or Publishing to multiple channels

### ISSUE THREAD

**Issue by franklevasseur** [fastly/pushpin#47983]
# Closing a single connection or Publishing to multiple channels

## Why

I'm writing a messaging app using Pushpin.

I have multiple **users** connecting to a single **conversation**. We want to implement a feature that allows removing a **user** from the **conversation**; the user should not receive any more messages. 

Currently my `Grip-Channel` is the conversation ID:

```typescript
{
  'Content-Type': 'text/event-stream',
  'Grip-Hold': 'stream',
  'Grip-Channel': `${conversationId}`,
}
```

Each user is a client with a connection on the conversation channel.

## What

To implement such a feature, I have few options:

### Option 1
Closing all connections on the channel, which would require all users to reconnect at the same time. This kind of sucks as it will increase the load on our backend and require some complicated logic in the client code.

### Option 2
I would need to close a single connection on the channel from the server (I'm don't believe this is doable with Pushpin)

### Option 3 
I would need to have a single channel per user (so it can be closed later) like

```typescript
{
  'Content-Type': 'text/event-stream',
  'Grip-Hold': 'stream',
  'Grip-Channel': `${conversationId}-${userId}`,
}
```

and when it's time to publish a new message I would do a database query to list all N users in the conversation and then publish the message N times (once for each user). This kind of sucks as it will increase the load on the pushpin instance, increase the amount of requests on the network and it would require extra database requests on the server side. 

### Option 4
Just like for option 3, I would need a single channel per user, but I would publish new messages on **all channels** of the conversation like:
 
 ```typescript
// POST /publish
 {
  items: [
    {
      channel: `${conversationId}-*`, // wild card channel pattern
      formats: {
        'http-stream': {
          content: "" // ...
        },
      },
    },
  ],
}
 ```

with some sort of channel wild card pattern...

This option is similar to https://github.com/fastly/pushpin/issues/47635, but the other way around (I want the publisher to publish to multiple channels with a wildcard.)

## Conclusion

Maybe I'm lacking imagination here, but these are the only ways I can think of implementing my feature, and obviously I would prefer option 2 or 4. Am I missing something ? What would be the usual way of handling such problems with Pushpin ?

Many thanks in advance for all help,

Frank

**Comment by jkarneges** [comment]
Option 2 is possible by subscribing each connection to both the shared conversation channel and a user-specific channel. Then if you want to kick off a particular user, you send a close action to their user-specific channel.

**Comment by franklevasseur** [comment]
Wow you are fast 😍

Ok so if I understand correctly what you're saying;

A channel is kind of an identifier of a connection, so if I publish a `close` action on the user-specific channel, it will close the entire connection (not just the user specific side) ?

**Comment by jkarneges** [comment]
Ah yes, that's right. The close action doesn't merely unsubscribe the one channel from the connection but rather it closes the entire connection, causing all of the connection's channels to be unsubscribed.

**Comment by franklevasseur** [comment]
That's perfect! Many thanks for your help,

You're the king 👑

**Comment by zuoike** [comment]
> That's perfect! Many thanks for your help,
> 
> You're the king 👑

@franklevasseur Please, did the method suggested work for you? I am asking because I want to implement same feature of *kicking off*! Thanks

**Comment by franklevasseur** [comment]
> @franklevasseur Please, did the method suggested work for you? I am asking because I want to implement same feature of *kicking off*! Thanks

Yes it does! It's currently running in production.

**Comment by zuoike** [comment]
Thanks, I tried it too and it worked perfectly.
