### ISSUE TITLE
How to link "publish queue at max" event with a specific connection

### ISSUE THREAD

**Issue by MauDagos** [fastly/pushpin#48022]
Hello,

We are seeing lots of these logs from Pushpin: `publish queue at max (10000 items), dropping`

In the past, with the help of the Pushpin team, we discovered that this log means that there's a connection that's not consuming messages quick enough, so Pushpin is dropping messages from the connection's output buffer. We would like to be able to link these logs to the specific connection. Is this possible right now or is it a feature request?

Thanks!

**Comment by jkarneges** [comment]
Hmm, that log message is different from what's in [the source](https://github.com/fastly/pushpin/blob/main/src/cpp/handler/httpsession.cpp#L516).

Maybe you're running a modified Pushpin? If so, you could modify it further to include other information.

**Comment by MauDagos** [comment]
Hello Justin,

Indeed, we were running a modified Pushpin. My question was on what type of objects in the code should we be looking at to try to pinpoint the specific slow connection.

In the end, we have decided to include the HTTP headers of the request in the log message, which gives us enough information. So, I'll resolve this issue.
